### ISSUE TITLE
Response is never given to the user

### ISSUE THREAD

**Issue by qlaffont** [rayriffy/elysia-rate-limit#18]
**Before open the issue**
- [X] I tried remove `node_modules/`, `bun.lockb`, and do a clean install.

**Describe the bug**
The response is not given (until it exceed the limit).

**To Reproduce**
1.  Clone 'https://github.com/qlaffont/starter-elysia/tree/master'
2. Uncomment `src/loader/RestLoader.ts` lines 2 & 12-37
3. `bun dev`
4. Go to `http://localhost:3000/ping`

**Expected behavior**
On call to /ping, should return `{ping : "pong"}`

**Comment by rayriffy** [comment]
Thanks for giving this reproduction project. I found out that this is an edge case of `@elysiajs/server-timing`. Already discussed with maintainer, will going to close this issue and re-open on elysia repository.

For now, just removing this tracing plugin will solve a problem.

**Comment by rayriffy** [comment]
Update for `elysia@1.0.10` is out. Please do clean install per checklist and try again.

**Comment by qlaffont** [comment]
Thanks I will try when I can !
