### ISSUE TITLE
[BUG] On limit exceeded, response is not given

### ISSUE THREAD

**Issue by qlaffont** [rayriffy/elysia-rate-limit#28]
**Before open the issue**
- [X] I tried remove `node_modules/`, `bun.lockb`, and do a clean installation.
- [X] I tried update Bun, and Elysia to latest version.

**Describe the bug**
When a user reach the limit, the response is never given

**To Reproduce**
Please provide a small reproduction project if possible. Steps to reproduce the behavior:
1. Go to 'https://github.com/qlaffont/starter-elysia'
2. Run `bun i && docker-compose up -d && cp .env.example .env && bun dev`
3. Go to `http://localhost:3000/swagger` and execute `/auth/login` with random password and email more than 6 times
4. You will see that the response is never given to the client on 6th time

**Expected behavior**
Return response 429 

**Environments**
1. Bun version: 1.1.0
2. Host Operating system: Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1711393930~22.04~331756a SMP PREEMPT_DYNAMIC Mon M x86_64 x86_64 x86_64 GNU/Linux
3. Running on Docker?: no

**Screenshots**
![image](https://github.com/rayriffy/elysia-rate-limit/assets/10044790/4486baae-1a51-457c-b537-c1df43cc7ae4)
![image](https://github.com/rayriffy/elysia-rate-limit/assets/10044790/a546b716-943a-4659-8abe-87dab81317b2)

**Additional Context**
For me I have checked source code, nothing seems strange or with bugs. So maybe elysia directly ?

**Comment by rayriffy** [comment]
Sorry, I got super busy with my work this week. I've confirmed that my rate-limit plugin already passed proper rate-limited response away from plugin properly. I found this empty response is quickly solved after remove `@elysiajs/server-timing` plugin from server. Definitely Elysia bug again, forwarding a bug to @saltyaom

![CleanShot 2024-04-10 at 01 39 21](https://github.com/rayriffy/elysia-rate-limit/assets/22584594/49a58709-5175-40ff-8e31-34cb1e3ac7b2)

**Comment by rayriffy** [comment]
Also related to https://github.com/rayriffy/elysia-rate-limit/issues/18

**Comment by qlaffont** [comment]
any update @SaltyAom ?

**Comment by rayriffy** [comment]
He's on holiday (me too). He'll be back next week.

**Comment by qlaffont** [comment]
any update @SaltyAom ?

**Comment by rayriffy** [comment]
1.1 just recently launched, can you try to confirm does this solves a problem?

**Comment by qlaffont** [comment]
No  @rayriffy error still present :/ (I have updated the repro)

**Comment by SaltyAom** [comment]
Should have been fixed on https://github.com/elysiajs/elysia/commit/ff73f8056ebd6e501e328b87b8a150aa6a194314, published on 1.0.16.

Please update and let me know if it works.
