### ISSUE TITLE
Elysia is not initialized yet. Please call .listen() first.

### ISSUE THREAD

**Issue by Huilensolis** [rayriffy/elysia-rate-limit#29]
**Before open the issue**
- [x] I tried remove `node_modules/`, `bun.lockb`, and do a clean installation.
- [x] I tried update Bun, and Elysia to latest version.

**Describe the bug**
when I use rateLimit on Elysia and I start the server with app.listen(), the rateLimit package plugin throws an error saying "Elysia is not initialized yet. Please call .listen() first."

**To Reproduce**
Please provide a small reproduction project if possible. Steps to reproduce the behavior:

```ts
const app = new Elysia()

app.group('/group', (app) =>
  app.use(
    rateLimit({
      duration: 1000 * 60 * 60 * 24, // a day
      max: 1000,
      generator: (req, server) => server?.requestIP(req)?.address ?? "",
    }),
  ).get('/', () => 'Hello World')
)

app.listen(3000)
```
then run the file with
```bash
bun --watch <path-to-the-file>
```

make a request to the endpoint
```bash
curl --request GET \
  --url http://localhost:3000/group/
```

and see the server logs:
```ts
    e:  9 |     options.context.init(options);
  10 |     return (app) => {
  11 |         app.onBeforeHandle({ as: 'global' }, async ({ set, request }) => {
  12 |             let clientKey;
  13 |             if (app.server === null)
  14 |                 throw new Error('Elysia is not initialized yet. Please call .listen() first.');
                             ^
  error: Elysia is not initialized yet. Please call .listen() first.
        at path-to-your-project/node_modules/elysia-rate-limit/dist/services/plugin.js:14:23
        at path-to-your-project/node_modules/elysia-rate-limit/dist/services/plugin.js:11:55
```

**Expected behavior**
don't throw an error saying you haven't called app.listen() if you indeed did.

**Environments**
1. Bun version: 1.0.35
2. Host Operating system: 
3. Running on Docker?: no

**Screenshots**
![image](https://github.com/rayriffy/elysia-rate-limit/assets/113150193/01c92649-2e3f-4e57-8166-a176c7895d1e)

**Additional context**

**Comment by Huilensolis** [comment]
running with elysia 1.0.9 btw

**Comment by Huilensolis** [comment]
any news on this? this broke my whole app. Any endpoint that uses rateLimit is not capable of receiving requests.

**Comment by rayriffy** [comment]
just release version `3.1.4`, now plugin no longer blocks you from making request when server is not defined. but be warned your app should be initialized already at this point.

**Comment by Huilensolis** [comment]
thank you for the quick fix!
I didn't understand the error message, what does "app should be initialized" mean? I have already called app.listen(3000)
