### ISSUE TITLE
duration overwritten

### ISSUE THREAD

**Issue by doroved** [rayriffy/elysia-rate-limit#37]
As a result, the duration in smsVerificationRoutes will be 200 seconds instead of 100, which is an error.
```ts
const smsVerificationRoutes = new Elysia()
  .use(rateLimit({
  duration: 100000
}))
  // your sms routes here

const apiRoutes = new Elysia()
  .use(rateLimit({
  duration: 200000
}))
  // your api routes here

const server = new Elysia()
  .use(smsVerificationRoutes)
  .use(apiRoutes)
  .listen(3000)
```

**smsVerificationRoutes**
Ratelimit-Reset:
200
Retry-After:
100

**apiRoutes**
Ratelimit-Reset:
200
Retry-After:
200

**Comment by rayriffy** [comment]
No that's not the behavior of rate limit at all. Rate limiting should be counted by time window, what you're asking right now is to give user a time out after certain request which is no longer a rate limiting anymore.

Thinking this scenario, with rate limit of 10 request with duration of 100 seconds

1. (0 sec) Make 2 requests
2. (400 sec) Make 7 request
3. (800 sec) Make 1 request
4. (801 sec) Make 1 request, get rate limited and waiting for 100 seconds
5. (901 sec) Make 1 request

This is 900 seconds time window, not 100 seconds

**Comment by rayriffy** [comment]
cookies are just http header, you can intercept and parse them via `request`
