### ISSUE TITLE
Duplicate run when use multiple time

### ISSUE THREAD

**Issue by armada45-pixel** [rayriffy/elysia-rate-limit#42]
**Before open the issue**
- [x] I tried remove `node_modules/`, `bun.lockb`, and do a clean installation.
- [x] I tried update Bun, and Elysia to latest version.

**Describe the bug**
Like title
Duplicate run when use multiple time
Issue example 
https://github.com/gaurishhs/elysia-ip/issues/18#issuecomment-2084854714

onBeforehandler will stack not repleace them seft **if** not using name in plugin instance
```ts
new Elysia()
```
and name it using 
```ts
new Elysia({ name: "elysia-rate-limit" })
```

**Screenshots**
![image](https://github.com/gaurishhs/elysia-ip/assets/59261678/adf22959-79c5-46f1-a5ec-7fef0ab9706e)

**Comment by armada45-pixel** [comment]
I'm in process will pull request soon.

**Comment by rayriffy** [comment]
small reproduction needed
