### ISSUE TITLE
Rate limiter missing client adress in Elysia sub-instance

### ISSUE THREAD

**Issue by hisamafahri** [rayriffy/elysia-rate-limit#48]
**Before open the issue**
- [x] I tried remove `node_modules/`, `bun.lockb`, and do a clean installation.
- [x] I tried update Bun, and Elysia to latest version.

**Describe the bug**
> Maybe related to #22 (?)

I use [controller pattern](https://elysiajs.com/essential/structure.html#controller), and notice that `elysia-rate-limit` will always fails to get the `server` instance is always `null` when tried to call `/test`

```
[elysia-rate-limit] failed to determine client address (reason: server is null)
```

**To Reproduce**
Use the following code:

```tsx
import { Elysia } from "elysia";
import { rateLimit } from "elysia-rate-limit";

const controller = new Elysia()
  .use(
    rateLimit({
      max: 5,
      errorResponse: new Response("Rate limiter invoked", {
        status: 429,
        headers: new Headers({
          "Content-Type": "text/plain",
        }),
      }),
    }),
  )
  .get("/test", () => "Hello, /test");

const app = new Elysia()
  .use(controller)
  .get("/", () => "Hello, world!")
  .listen(3000);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`,
);
```

1. Make sure bun, elysia, and `elysia-rate-limit` is installed, and add code above to `src/index.ts`
2. Run dev (`bun dev`) and call `GET /test`
3. See error on terminal console and rate limiter never invoked

**Expected behavior**
Rate limiter called and invoked

**Environments**
1. Bun version: `1.1.27`
2. Host Operating system: `Apple MacOS, Sequoia 15.2, Darwin 24.2.0 arm64 arm`
3. elysia: `1.1.25`
4. `elysia-rate-limit`: `4.1.0`
5. Running on Docker?: no

**Additional info**
Adding `rateLimit` to the root of `Elysia()` instance:
```tsx
const app = new Elysia()
  .use(
    rateLimit({
      max: 5,
      errorResponse: new Response("Root level rate limiter", {
        status: 429,
        headers: new Headers({
          "Content-Type": "text/plain",
        }),
      }),
    }),
  )
  .use(controller)
  .get("/", () => "Rate limit OK")
  .listen(3000);
```

It "work" (meaning that the rate limiter invoked). But it only follows the config from the main `Elysia()` instance. And _all _ the sub `elysia-rate-limit` config are being completely ignored.

**Comment by rayriffy** [comment]
Can you help trying `injectServer` option to see would it solves an issue? [Examples](https://github.com/rayriffy/elysia-rate-limit/blob/main/example/multiInstanceInjected.ts)
