### ISSUE TITLE
Support for Elysia 0.8

### ISSUE THREAD

**Issue by tnfAngel** [rayriffy/elysia-rate-limit#7]
The plugin does not work with Elysia 0.8
![imagen](https://github.com/rayriffy/elysia-rate-limit/assets/57068341/08529069-8ee4-4376-b986-3e1fbea96716)

**Comment by rayriffy** [comment]
Hello, I am just gone back from long holiday. I will look into this asap.

**Comment by rayriffy** [comment]
Hey, I've created an empty Elysia 0.8 project and plugins are works just fine. Please try removing `node_modules` and `bun.lockb`, then do a clean `bun install`. If issue still persists, please re-open this issue with small project than reproduce this issue.

![CleanShot 2024-01-06 at 16 17 48](https://github.com/rayriffy/elysia-rate-limit/assets/22584594/a0142409-9672-415c-9668-a1c82c093e0c)
