### ISSUE TITLE
Unable to determine client IP

### ISSUE THREAD

**Issue by samyung0** [rayriffy/elysia-rate-limit#8]
I am currently using bun 1.0.22,  elysia 0.8.8 and elysia rate limit 2.0.1.
I am using it like this
```ts
.use(
    rateLimit({
      duration: 10000,
    })
  )
```
and it is showing in the terminal:
`[elysia-rate-limit] generator is unable to determine client IP address. Are you using older version of Bun?`

**Comment by rayriffy** [comment]
Which platform has you deployed to in order to get this error?

**Comment by samyung0** [comment]
The issue went away after reinstalling everything. Sorry for the confusion.
