### ISSUE TITLE
Use LRU cache for default context

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [rayriffy/elysia-rate-limit#9]
**Is your feature request related to a problem? Please describe.**
The default context doesn't have a memory limit, which can be problematic when a server is heavily requested.

**Describe the solution you'd like**
That the default context uses a cache with a limit you can customize so you can control the max memory it will use.

**Describe alternatives you've considered**
The other option would be to let users implement it themselves on their own context, but I think it's a good default to have.

**Additional context**
The idea would be to use a lru cache, [like @fastify/rate-limit does](https://github.com/fastify/fastify-rate-limit/blob/89a618f610801f5b05db6f51c75e776cd94e64af/store/LocalStore.js#L3C1-L4C1), and then add a new option like `cache` where you can customize to size of the cache.

Happy to do a PR if this is approved.

**Comment by rayriffy** [comment]
we already have the way to implement our own strategy, is [`context`](https://github.com/rayriffy/elysia-rate-limit?tab=readme-ov-file#context) sufficient enough for you? happy to take in feedback

**Comment by ricardo-devis-agullo** [comment]
Yeah, that is an option, I just think it's better to have as a default a limit on memory so the default usage will not spiral out of memory, and if you don't want to have a limit you could implement your own strategy, but up to you what you think is a better default!

**Comment by rayriffy** [comment]
Hey, it's been a while but now I got a bit of my time to working on this. I've implemented a new caching strategy as requested and published in version `3.1.0-beta.0`. Could you try this out if it works for you?

**Comment by ricardo-devis-agullo** [comment]
code looks fine but I think you didnt ship the dist folder to npm :)

**Comment by rayriffy** [comment]
Whoops, I'll merge it then. I already tested it's functionality.
